// <auto-generated />
using System;
using BookingApp.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookingApp.Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241214202419_AddAmenityToDb")]
    partial class AddAmenityToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.3.24172.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookingApp.Domain.Entities.Amenity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("Amenities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Private Pool",
                            PropertyId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Microwave",
                            PropertyId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Private Balcony",
                            PropertyId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "1 king bed and 1 sofa bed",
                            PropertyId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "Private Plunge Pool",
                            PropertyId = 2
                        },
                        new
                        {
                            Id = 6,
                            Name = "Microwave and Mini Refrigerator",
                            PropertyId = 2
                        },
                        new
                        {
                            Id = 7,
                            Name = "Private Balcony",
                            PropertyId = 2
                        },
                        new
                        {
                            Id = 8,
                            Name = "king bed or 2 double beds",
                            PropertyId = 2
                        },
                        new
                        {
                            Id = 9,
                            Name = "Private Pool",
                            PropertyId = 3
                        },
                        new
                        {
                            Id = 10,
                            Name = "Jacuzzi",
                            PropertyId = 3
                        },
                        new
                        {
                            Id = 11,
                            Name = "Private Balcony",
                            PropertyId = 3
                        });
                });

            modelBuilder.Entity("BookingApp.Domain.Entities.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Occupancy")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("SquareMeters")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Description for Premium Pool Villa",
                            ImageUrl = "https://placehold.co/600x401",
                            Name = "Premium Pool Villa",
                            Occupancy = 3.0,
                            Price = 1000.0,
                            SquareMeters = 100.0
                        },
                        new
                        {
                            Id = 2,
                            Description = "Description for Austrian Villa",
                            ImageUrl = "https://placehold.co/600x402",
                            Name = "Austrian Villa",
                            Occupancy = 2.0,
                            Price = 2000.0,
                            SquareMeters = 200.0
                        },
                        new
                        {
                            Id = 3,
                            Description = "Description for Italian Villa",
                            ImageUrl = "https://placehold.co/600x403",
                            Name = "Italian Villa",
                            Occupancy = 1.0,
                            Price = 3000.0,
                            SquareMeters = 300.0
                        });
                });

            modelBuilder.Entity("BookingApp.Domain.Entities.PropertyNumber", b =>
                {
                    b.Property<int>("PropertyNr")
                        .HasColumnType("int");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<string>("SpecialDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("PropertyNr");

                    b.HasIndex("PropertyId");

                    b.ToTable("PropertyNumbers");

                    b.HasData(
                        new
                        {
                            PropertyNr = 101,
                            PropertyId = 1,
                            Type = 0
                        },
                        new
                        {
                            PropertyNr = 102,
                            PropertyId = 1,
                            Type = 0
                        },
                        new
                        {
                            PropertyNr = 103,
                            PropertyId = 1,
                            Type = 0
                        },
                        new
                        {
                            PropertyNr = 201,
                            PropertyId = 2,
                            Type = 0
                        },
                        new
                        {
                            PropertyNr = 202,
                            PropertyId = 2,
                            Type = 0
                        },
                        new
                        {
                            PropertyNr = 203,
                            PropertyId = 2,
                            Type = 0
                        },
                        new
                        {
                            PropertyNr = 301,
                            PropertyId = 3,
                            Type = 0
                        },
                        new
                        {
                            PropertyNr = 302,
                            PropertyId = 3,
                            Type = 0
                        });
                });

            modelBuilder.Entity("BookingApp.Domain.Entities.Amenity", b =>
                {
                    b.HasOne("BookingApp.Domain.Entities.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("BookingApp.Domain.Entities.PropertyNumber", b =>
                {
                    b.HasOne("BookingApp.Domain.Entities.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });
#pragma warning restore 612, 618
        }
    }
}
